### ISSUE TITLE
Order status not getting changed after successful payment

### ISSUE THREAD

**Issue by Hari-Bonda** [payumoney-india/woocommerceplugin-2.x#1]
Order status is not getting changed to Processing after successful payment.
Order notes are not getting updated with payment info like payment ID or payment date

**Comment by amolsaini** [comment]
I am having the same problem.

**Comment by Hari-Bonda** [comment]
> I am having the same problem.

Start a new support ticket .. they will help you. but in my case, they sent me the latest updated WordPress WooCommerce plugin via email .. I don't remember. but everything works perfectly with "WooCommerce PayUmoney BOLT with Shiprocket > Version 2.6"
